name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cd cli && cargo build --verbose

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build release
      run: cd cli && cargo build --release

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cli/target/release/tdx-measure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
